# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Feature Carousel
  description: A horizontal carousel to showcase feature cards or minutes with a download button.
  icon: "view_carousel"
  tags: ["feature", "carousel"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Feature Carousel
  image: /images/feature/feature-card-one.png
  items:
    - title: "Card 1"
      description: "Short description for card 1"
      link: "/"
    - title: "Card 2"
      description: "Short description for card 2"
      link: "/"
    - title: "Card 3"
      description: "Short description for card 3"
      link: "/"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
  image:
    type: image
    comment: "This image will be used for all carousel cards"
  items:
    type: array
    fields:
      - name: title
        type: text
      - name: description
        type: textarea
      - name: link
        type: text
