- name: Detect package manager
  id: detect-package-manager
  working-directory: ${{ env.BUILD_PATH }}
  run: |
    set -euo pipefail

    echo "Listing files for sanity:"
    pwd
    ls -la

    if [ -f "yarn.lock" ]; then
      {
        echo "manager=yarn"
        echo "command=install"
        echo "runner=yarn"
        echo "lockfile=yarn.lock"
      } >> "$GITHUB_OUTPUT"
    elif [ -f "package-lock.json" ]; then
      {
        echo "manager=npm"
        echo "command=ci"
        echo "runner=npx --no-install"
        echo "lockfile=package-lock.json"
      } >> "$GITHUB_OUTPUT"
    elif [ -f "pnpm-lock.yaml" ]; then
      {
        echo "manager=pnpm"
        echo "command=install --frozen-lockfile"
        echo "runner=pnpm"
        echo "lockfile=pnpm-lock.yaml"
      } >> "$GITHUB_OUTPUT"
    else
      echo "Unable to determine package manager in $(pwd)" >&2
      exit 1
    fi

